// <auto-generated />
using System;
using FictionBranches.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FictionBranches.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("hibernate_sequence");

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbannouncement", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.HasKey("Id")
                        .HasName("fbannouncements_pkey");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_fbannouncements_authorid");

                    b.ToTable("fbannouncements", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbannouncementview", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("AnnouncementId")
                        .HasColumnType("bigint")
                        .HasColumnName("announcement_id");

                    b.Property<string>("ViewerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("viewer_id");

                    b.HasKey("Id")
                        .HasName("fbannouncementviews_pkey");

                    b.HasIndex("AnnouncementId")
                        .HasDatabaseName("ix_fbannouncementviews_announcementid");

                    b.HasIndex("ViewerId")
                        .HasDatabaseName("ix_fbannouncementviews_viewerid");

                    b.ToTable("fbannouncementviews", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbarchivetoken", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("fbarchivetokens_pkey");

                    b.HasIndex(new[] { "Token" }, "uk_2fq2h3p230ef6p1boflsarg64")
                        .IsUnique()
                        .HasDatabaseName("ix_fbarchivetokens_token");

                    b.ToTable("fbarchivetokens", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbauthorsubscription", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Createddate")
                        .HasColumnType("bigint")
                        .HasColumnName("createddate");

                    b.Property<string>("SubscribedtoId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subscribedto_id");

                    b.Property<string>("SubscriberId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subscriber_id");

                    b.HasKey("Id")
                        .HasName("fbauthorsubscriptions_pkey");

                    b.HasIndex("SubscribedtoId")
                        .HasDatabaseName("ix_fbauthorsubscriptions_subscribedto_id");

                    b.HasIndex(new[] { "SubscriberId", "SubscribedtoId" }, "uka07ci6945k3kc3hf1qxb7pk7m")
                        .IsUnique()
                        .HasDatabaseName("ix_fbauthorsubscriptions_subscriberid_subscribedtoid");

                    b.ToTable("fbauthorsubscriptions", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbcomment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("editdate");

                    b.Property<string>("EditorId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("editor_id");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<bool>("Modvoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("modvoice");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbcomments_pkey");

                    b.HasIndex("EditorId")
                        .HasDatabaseName("ix_fbcomments_editor_id");

                    b.HasIndex("EpisodeGeneratedid")
                        .HasDatabaseName("ix_fbcomments_episode_generatedid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbcomments_user_id");

                    b.ToTable("fbcomments", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbcommentsub", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbcommentsubs_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbcommentsubs_userid");

                    b.HasIndex(new[] { "EpisodeGeneratedid", "UserId" }, "uk1fi8d6b10aqv1ax6mk14kplnf")
                        .IsUnique()
                        .HasDatabaseName("ix_fbcommentsubs_episodegeneratedid_userid");

                    b.ToTable("fbcommentsubs", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbemailchange", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Newemail")
                        .HasColumnType("text")
                        .HasColumnName("newemail");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Token")
                        .HasName("fbemailchanges_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbemailchanges_userid");

                    b.ToTable("fbemailchanges", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbepisode", b =>
                {
                    b.Property<long>("Generatedid")
                        .HasColumnType("bigint")
                        .HasColumnName("generatedid");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("Childcount")
                        .HasColumnType("integer")
                        .HasColumnName("childcount");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("editdate");

                    b.Property<string>("EditorId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("editor_id");

                    b.Property<string>("Legacyid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("legacyid");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link");

                    b.Property<string>("Newmap")
                        .HasColumnType("text")
                        .HasColumnName("newmap");

                    b.Property<string>("Oldmap")
                        .HasColumnType("text")
                        .HasColumnName("oldmap");

                    b.Property<long?>("ParentGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_generatedid");

                    b.Property<DateTime?>("Tagdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tagdate");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<long>("Viewcount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("viewcount");

                    b.HasKey("Generatedid")
                        .HasName("fbepisodes_pkey");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_fbepisodes_author_id");

                    b.HasIndex("EditorId")
                        .HasDatabaseName("ix_fbepisodes_editor_id");

                    b.HasIndex("ParentGeneratedid")
                        .HasDatabaseName("ix_fbepisodes_parentgeneratedid");

                    b.HasIndex(new[] { "Date" }, "ep_date_index")
                        .HasDatabaseName("ix_fbepisodes_date");

                    b.HasIndex(new[] { "Oldmap" }, "uk_5kqds4rxwiq5qh15urpctlac2")
                        .IsUnique()
                        .HasDatabaseName("ix_fbepisodes_oldmap");

                    b.ToTable("fbepisodes", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbepisodetag", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<long?>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.Property<string>("TaggedbyId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("taggedby_id");

                    b.Property<long>("Taggeddate")
                        .HasColumnType("bigint")
                        .HasColumnName("taggeddate");

                    b.HasKey("Id")
                        .HasName("fbepisodetags_pkey");

                    b.HasIndex(new[] { "TagId" }, "idx6glbrb9706ndl78n4po1q31p3")
                        .HasDatabaseName("ix_fbepisodetags_tagid");

                    b.HasIndex(new[] { "TaggedbyId" }, "idx6wbgto5he13slswpm3muantap")
                        .HasDatabaseName("ix_fbepisodetags_taggedbyid");

                    b.HasIndex(new[] { "EpisodeGeneratedid" }, "idxclrec9v1rw5348dw9bjvas1tj")
                        .HasDatabaseName("ix_fbepisodetags_episodegeneratedid");

                    b.HasIndex(new[] { "Taggeddate" }, "idxfxkct3g8hdmh07qroh0hmgbgo")
                        .HasDatabaseName("ix_fbepisodetags_taggeddate");

                    b.HasIndex(new[] { "EpisodeGeneratedid", "TagId" }, "uk5095m2mxm9rkn4ksataksfr0")
                        .IsUnique()
                        .HasDatabaseName("ix_fbepisodetags_episodegeneratedid_tagid");

                    b.ToTable("fbepisodetags", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbepisodeview", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbepisodeviews_pkey");

                    b.HasIndex(new[] { "Date" }, "idx4075itwl1o036bys3ds2tsp60")
                        .HasDatabaseName("ix_fbepisodeviews_date");

                    b.HasIndex(new[] { "UserId" }, "idx9fjwfue99stcs4sxnijwuc4k0")
                        .HasDatabaseName("ix_fbepisodeviews_userid");

                    b.HasIndex(new[] { "EpisodeGeneratedid" }, "idxccvjbggf4me4vbhhokfcxw4bg")
                        .HasDatabaseName("ix_fbepisodeviews_episodegeneratedid");

                    b.HasIndex(new[] { "EpisodeGeneratedid", "UserId" }, "ukbhxqnt6rnqbmssnsbo9490wou")
                        .IsUnique()
                        .HasDatabaseName("ix_fbepisodeviews_episodegeneratedid_userid");

                    b.ToTable("fbepisodeviews", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbfailedloginattempt", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Ip")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ip");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("fbfailedloginattempts_pkey");

                    b.ToTable("fbfailedloginattempts", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbfavep", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbfaveps_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbfaveps_userid");

                    b.HasIndex(new[] { "EpisodeGeneratedid", "UserId" }, "ukkj448x377yghlrgiqyq5kjyr8")
                        .IsUnique()
                        .HasDatabaseName("ix_fbfaveps_episodegeneratedid_userid");

                    b.ToTable("fbfaveps", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbflaggedcomment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbflaggedcomments_pkey");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_fbflaggedcomments_commentid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbflaggedcomments_userid");

                    b.ToTable("fbflaggedcomments", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbflaggedepisode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbflaggedepisodes_pkey");

                    b.HasIndex("EpisodeGeneratedid")
                        .HasDatabaseName("ix_fbflaggedepisodes_episodegeneratedid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbflaggedepisodes_userid");

                    b.ToTable("fbflaggedepisodes", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbloginban", b =>
                {
                    b.Property<string>("Ip")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ip");

                    b.Property<int>("Bancount")
                        .HasColumnType("integer")
                        .HasColumnName("bancount");

                    b.Property<long>("Until")
                        .HasColumnType("bigint")
                        .HasColumnName("until");

                    b.HasKey("Ip")
                        .HasName("fbloginbans_pkey");

                    b.ToTable("fbloginbans", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbmodepisode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("fbmodepisodes_pkey");

                    b.HasIndex("EpisodeGeneratedid")
                        .HasDatabaseName("ix_fbmodepisodes_episodegeneratedid");

                    b.ToTable("fbmodepisodes", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbnotification", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool?>("Approved")
                        .HasColumnType("boolean")
                        .HasColumnName("approved");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean")
                        .HasColumnName("read");

                    b.Property<string>("SenderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_id");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbnotifications_pkey");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_fbnotifications_commentid");

                    b.HasIndex("EpisodeGeneratedid")
                        .HasDatabaseName("ix_fbnotifications_episodegeneratedid");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_fbnotifications_sender_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbnotifications_user_id");

                    b.ToTable("fbnotifications", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbpasswordreset", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Token")
                        .HasName("fbpasswordresets_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_fbpasswordresets_userid");

                    b.ToTable("fbpasswordresets", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbpotentialuser", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Passwordhash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Token")
                        .HasName("fbpotentialusers_pkey");

                    b.ToTable("fbpotentialusers", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbrecentuserblock", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BlockeduserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("blockeduser_id");

                    b.Property<string>("BlockinguserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("blockinguser_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.HasKey("Id")
                        .HasName("fbrecentuserblocks_pkey");

                    b.HasIndex("BlockeduserId")
                        .HasDatabaseName("ix_fbrecentuserblocks_blockeduser_id");

                    b.HasIndex("BlockinguserId")
                        .HasDatabaseName("ix_fbrecentuserblocks_blockinguser_id");

                    b.ToTable("fbrecentuserblocks", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbsitesetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("fbsitesettings_pkey");

                    b.ToTable("fbsitesettings", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbtag", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CreatedbyId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby_id");

                    b.Property<long>("Createddate")
                        .HasColumnType("bigint")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EditedbyId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("editedby_id");

                    b.Property<long>("Editeddate")
                        .HasColumnType("bigint")
                        .HasColumnName("editeddate");

                    b.Property<string>("Longname")
                        .HasColumnType("text")
                        .HasColumnName("longname");

                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shortname");

                    b.HasKey("Id")
                        .HasName("fbtags_pkey");

                    b.HasIndex("CreatedbyId")
                        .HasDatabaseName("ix_fbtags_createdby_id");

                    b.HasIndex("EditedbyId")
                        .HasDatabaseName("ix_fbtags_editedby_id");

                    b.HasIndex(new[] { "Shortname" }, "idxrqjtrdudtdg2yocvvngu48r71")
                        .HasDatabaseName("ix_fbtags_shortname");

                    b.HasIndex(new[] { "Shortname" }, "uk_crm05y4qlhyhltl6n83qneeeu")
                        .IsUnique()
                        .HasDatabaseName("ix_fbtags_shortname1");

                    b.ToTable("fbtags", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbtheme", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Css")
                        .HasColumnType("text")
                        .HasColumnName("css");

                    b.HasKey("Name")
                        .HasName("fbthemes_pkey");

                    b.ToTable("fbthemes", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbupvote", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<long?>("EpisodeGeneratedid")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_generatedid");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("fbupvotes_pkey");

                    b.HasIndex(new[] { "EpisodeGeneratedid" }, "idx6ptpvnyrxr7d12ntoflbcav3f")
                        .HasDatabaseName("ix_fbupvotes_episodegeneratedid");

                    b.HasIndex(new[] { "Date" }, "idxbbfnbongm0jrh0nqqh6u2gjuo")
                        .HasDatabaseName("ix_fbupvotes_date");

                    b.HasIndex(new[] { "UserId" }, "idxf63lcdws5rerv7a8cwjvfif2q")
                        .HasDatabaseName("ix_fbupvotes_userid");

                    b.HasIndex(new[] { "EpisodeGeneratedid", "UserId" }, "uk3usmmoftdasoxog2jp7o3mipd")
                        .IsUnique()
                        .HasDatabaseName("ix_fbupvotes_episodegeneratedid_userid");

                    b.ToTable("fbupvotes", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbuser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<bool?>("Authorsubmail")
                        .HasColumnType("boolean")
                        .HasColumnName("authorsubmail");

                    b.Property<bool?>("Authorsubsite")
                        .HasColumnType("boolean")
                        .HasColumnName("authorsubsite");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int?>("Bodytextwidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(900)
                        .HasColumnName("bodytextwidth");

                    b.Property<bool>("Childmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("childmail");

                    b.Property<bool>("Childsite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("childsite");

                    b.Property<bool>("Commentmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("commentmail");

                    b.Property<bool>("Commentsite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("commentsite");

                    b.Property<string>("ConcurrencyStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<bool>("Hideimages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hideimages");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutend");

                    b.Property<string>("NormalizedEmail")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalizedemail")
                        .HasComputedColumnSql("UPPER([email])");

                    b.Property<string>("NormalizedUserName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalizedusername")
                        .HasComputedColumnSql("UPPER([id])");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<string>("SecurityStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("securitystamp")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("Theme")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("theme");

                    b.Property<string>("ThemeName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("theme_name");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twofactorenabled");

                    b.HasKey("Id")
                        .HasName("fbusers_pkey");

                    b.HasIndex("ThemeName")
                        .HasDatabaseName("ix_fbusers_theme_name");

                    b.HasIndex(new[] { "Email" }, "uk_6uw40lt55at3tt4qc1ypxaqj5")
                        .IsUnique()
                        .HasDatabaseName("ix_fbusers_email");

                    b.ToTable("fbusers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text")
                        .HasColumnName("normalizedname");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("Id")
                        .HasName("pk_roleclaims");

                    b.ToTable("roleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_userclaims");

                    b.ToTable("userclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("providerdisplayname");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_userlogins");

                    b.ToTable("userlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_userroles");

                    b.ToTable("userroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usertokens");

                    b.ToTable("usertokens", (string)null);
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbannouncement", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Author")
                        .WithMany("Fbannouncements")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk3xe75e0j9yttkprse44df77p9");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbannouncementview", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbannouncement", "Announcement")
                        .WithMany("Fbannouncementviews")
                        .HasForeignKey("AnnouncementId")
                        .HasConstraintName("fknshw2jucw1p0s2cjq1wawj2wn");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Viewer")
                        .WithMany("Fbannouncementviews")
                        .HasForeignKey("ViewerId")
                        .HasConstraintName("fk4ney7yabt558kvopprhqhr33b");

                    b.Navigation("Announcement");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbauthorsubscription", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Subscribedto")
                        .WithMany("FbauthorsubscriptionSubscribedtos")
                        .HasForeignKey("SubscribedtoId")
                        .HasConstraintName("fkgbm3ft2df9nebw67f47yguoah");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Subscriber")
                        .WithMany("FbauthorsubscriptionSubscribers")
                        .HasForeignKey("SubscriberId")
                        .HasConstraintName("fk7gq1evpy1cr9mxvplnxxupana");

                    b.Navigation("Subscribedto");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbcomment", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Editor")
                        .WithMany("FbcommentEditors")
                        .HasForeignKey("EditorId")
                        .HasConstraintName("fk6rnmixm3m4dk7krre8atdctbs");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbcomments")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fk344ylqk2chdvhmirf7076wqp6");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("FbcommentUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkfwppbf9bst2pk7cf77cj58w8e");

                    b.Navigation("Editor");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbcommentsub", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbcommentsubs")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fk9plrw0erv21vd4kq60993k520");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbcommentsubs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkqaru6fiei0w9qtxisx4q564sk");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbemailchange", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbemailchanges")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkdsbx42chvw1x9ppa19cpri4g8");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbepisode", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Author")
                        .WithMany("FbepisodeAuthors")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk59nj53wh7qlje013erl884kbf");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Editor")
                        .WithMany("FbepisodeEditors")
                        .HasForeignKey("EditorId")
                        .HasConstraintName("fkf2531iimwtfmjwwy8y0pj6r5k");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "ParentGenerated")
                        .WithMany("InverseParentGenerated")
                        .HasForeignKey("ParentGeneratedid")
                        .HasConstraintName("fk9g5au8ye310xeaa88f23in3vv");

                    b.Navigation("Author");

                    b.Navigation("Editor");

                    b.Navigation("ParentGenerated");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbepisodetag", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbepisodetags")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fkckw00wx70serlw1kbawbcu7wk");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbtag", "Tag")
                        .WithMany("Fbepisodetags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("fkqkytddc188eqxtuxnbywoiq42");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Taggedby")
                        .WithMany("Fbepisodetags")
                        .HasForeignKey("TaggedbyId")
                        .HasConstraintName("fk6qb905bt9nkjiunnmovpj0rdf");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("Tag");

                    b.Navigation("Taggedby");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbepisodeview", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbepisodeviews")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fkihpilnxwx6i1xeamjb1kl6bs1");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbepisodeviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkmyl1oym9gfcgr5vd4ifkka9bo");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbfavep", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbfaveps")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fk7om33wahqw6v55fievvb2icme");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbfaveps")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkeyolm2p18u6mqj8d5id9mlxqy");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbflaggedcomment", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbcomment", "Comment")
                        .WithMany("Fbflaggedcomments")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("fkotxfof7l9ns5q46qh2d2ptuym");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbflaggedcomments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fks7fhiw81skw4d3b637w58d2tq");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbflaggedepisode", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbflaggedepisodes")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fkokgei59wft1f1jmxd8bthh4i5");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbflaggedepisodes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkc9u2mpdi6wk3u5dffth6465fq");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbmodepisode", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbmodepisodes")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fk6j9revek9um6a702pevgoqs6s");

                    b.Navigation("EpisodeGenerated");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbnotification", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbcomment", "Comment")
                        .WithMany("Fbnotifications")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("fkg6rr20rd7ko6xivl84vmdk4ah");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbnotifications")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fk7ceksuy8hd0ai32ginrgp09u2");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Sender")
                        .WithMany("FbnotificationSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("fkr67sxjjp5uvex1x3ta4s2sfb6");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("FbnotificationUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkmxxr1jnbawose6dku5ue6oq91");

                    b.Navigation("Comment");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("Sender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbpasswordreset", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbpasswordresets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fkg2sdbvhjp1eu110rxipqr3r6u");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbrecentuserblock", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Blockeduser")
                        .WithMany("FbrecentuserblockBlockedusers")
                        .HasForeignKey("BlockeduserId")
                        .HasConstraintName("fkrqbktmevocrexrdtnw4l8y8ht");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Blockinguser")
                        .WithMany("FbrecentuserblockBlockingusers")
                        .HasForeignKey("BlockinguserId")
                        .HasConstraintName("fkp0tbw069wnvhbdwhuwpg9o2qm");

                    b.Navigation("Blockeduser");

                    b.Navigation("Blockinguser");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbtag", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Createdby")
                        .WithMany("FbtagCreatedbies")
                        .HasForeignKey("CreatedbyId")
                        .HasConstraintName("fk7l099dekvrnwg001ly43o69sq");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "Editedby")
                        .WithMany("FbtagEditedbies")
                        .HasForeignKey("EditedbyId")
                        .HasConstraintName("fk7p4031xej38cy0hvagdsyoc5a");

                    b.Navigation("Createdby");

                    b.Navigation("Editedby");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbupvote", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbepisode", "EpisodeGenerated")
                        .WithMany("Fbupvotes")
                        .HasForeignKey("EpisodeGeneratedid")
                        .HasConstraintName("fk6t4ojhv1x4tohfk71j2tsfok8");

                    b.HasOne("FictionBranches.Web.Data.Models.Fbuser", "User")
                        .WithMany("Fbupvotes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk440roqsvo8qhv08hl9u1y8dgs");

                    b.Navigation("EpisodeGenerated");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbuser", b =>
                {
                    b.HasOne("FictionBranches.Web.Data.Models.Fbtheme", "ThemeNameNavigation")
                        .WithMany("Fbusers")
                        .HasForeignKey("ThemeName")
                        .HasConstraintName("fkrbykt6si6h8et3vny0uyfhvi2");

                    b.Navigation("ThemeNameNavigation");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbannouncement", b =>
                {
                    b.Navigation("Fbannouncementviews");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbcomment", b =>
                {
                    b.Navigation("Fbflaggedcomments");

                    b.Navigation("Fbnotifications");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbepisode", b =>
                {
                    b.Navigation("Fbcomments");

                    b.Navigation("Fbcommentsubs");

                    b.Navigation("Fbepisodetags");

                    b.Navigation("Fbepisodeviews");

                    b.Navigation("Fbfaveps");

                    b.Navigation("Fbflaggedepisodes");

                    b.Navigation("Fbmodepisodes");

                    b.Navigation("Fbnotifications");

                    b.Navigation("Fbupvotes");

                    b.Navigation("InverseParentGenerated");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbtag", b =>
                {
                    b.Navigation("Fbepisodetags");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbtheme", b =>
                {
                    b.Navigation("Fbusers");
                });

            modelBuilder.Entity("FictionBranches.Web.Data.Models.Fbuser", b =>
                {
                    b.Navigation("Fbannouncements");

                    b.Navigation("Fbannouncementviews");

                    b.Navigation("FbauthorsubscriptionSubscribedtos");

                    b.Navigation("FbauthorsubscriptionSubscribers");

                    b.Navigation("FbcommentEditors");

                    b.Navigation("FbcommentUsers");

                    b.Navigation("Fbcommentsubs");

                    b.Navigation("Fbemailchanges");

                    b.Navigation("FbepisodeAuthors");

                    b.Navigation("FbepisodeEditors");

                    b.Navigation("Fbepisodetags");

                    b.Navigation("Fbepisodeviews");

                    b.Navigation("Fbfaveps");

                    b.Navigation("Fbflaggedcomments");

                    b.Navigation("Fbflaggedepisodes");

                    b.Navigation("FbnotificationSenders");

                    b.Navigation("FbnotificationUsers");

                    b.Navigation("Fbpasswordresets");

                    b.Navigation("FbrecentuserblockBlockedusers");

                    b.Navigation("FbrecentuserblockBlockingusers");

                    b.Navigation("FbtagCreatedbies");

                    b.Navigation("FbtagEditedbies");

                    b.Navigation("Fbupvotes");
                });
#pragma warning restore 612, 618
        }
    }
}
